set nocompatible

" Automatic formatting
autocmd BufWritePre *.rb :%s/\s\+$//e
autocmd BufWritePre *.html :%s/\s\+$//e
autocmd BufWritePre *.html :%s/\s\+$//e
au BufRead,BufNewFile Rakefile setf ruby
au BufRead,BufNewFile Guardfile setf ruby
au BufRead,BufNewFile Gemfile setf ruby
au BufRead,BufNewFile Procfile setf yaml
au BufNewFile,BufRead *.rabl setf ruby
au BufNewFile,BufRead *.rhtml set syn=eruby
au BufNewFile,BufRead *.erb set syn=eruby
au BufNewFile,BufRead *.json setf javascript
au BufNewFile,BufRead *.coffee setf coffee

syntax on 				" Syntax highlighting

set tabstop=2
set shiftwidth=2
set softtabstop=2
set backspace=indent,eol,start
set expandtab				        " Uses spaces instead of tabs
set smarttab				        " let's tab key insert 'tab stops', and bksp deletes tabs
set shiftround				      " tab / shifting moves to closest tabstop.

set history=1000            " remember more commands and search history
set undolevels=1000         " use many muchos levels of undo

set autoindent				      " Match indents on new lines.
set smartindent				      " Intelligently dedent / indent new lines based on rules.
set showmatch               " Show matching brackets when text indicator is over them

set splitright              " put new windows on the right
set splitbelow              " and below
set clipboard=unnamed       " OS X clipboard integration

set wildmenu                "make tab completion behave like bash
set wildmode=list:longest,full
set wildignore+=.hg,.git,.svn
set wildignore+=*.jpg,*.bmp,*.gif,*.png,*.jpeg
set wildignore+=*.sw?
set wildignore+=*.DS_Store?
set wildignore+=vendor/bundle
set wildignore+=vendor/gems

" Start scrolling three lines before the horizontal window border 
set scrolloff=5

" We have VCS -- we don't need this
set nobackup				        " we have vcs
set nowritebackup			      " we have vcs
set noswapfile
set nohidden				        " Do NOT  allow me to have buffers with unsaved changes

" don't nag me when hiding buffers
set autoread				        " when a file has changed on disk, just load it. Don't ask
set autowrite               " autmotically write the file when leaving a modified buffe
"set autowriteall            " automatically write a file when leaving vim

" Make search more sane
set ignorecase				      " case insensitive search
set smartcase				        " If there are uppercase letters, become case-sensitive
set showmatch				        " live match highlighting
set showcmd                 " show incomplete command
set noshowmode              " disables the command mode from displaying
set incsearch				        " live incremental searching
set hlsearch				        " hightlight matches
set gdefault				        " use the `g` flag by default
set nu                      " show line number
set ruler                   " show row and column number
set laststatus=2            " always shows the status line

" allow the cursor to go anywhere in visual block mode
set virtualedit+=block

" leader is a key that allows you to have your own 'namespace" of keybindings.
" You'll see it a lot below as <leader>
let mapleader = ","

" So we don't have to press shift when we want to get into command mode.
" nnoremap ; :
" vnoremap ; :

" So we don't have to reach for escape to leave insert move.
inoremap jj <esc>

" create new vsplit, and switch to it
noremap <leader>v <C-w>v<C-w>l
noremap <leader>s <C-w>s<C-w>j

" bindings for easy split nav
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" use sane regex's when searching
nnoremap / /\v
vnoremap / /\v

" clear match highlighting
noremap <leader><space> :noh<cr>:call clearmatches()<cr>

" Quick buffer switching - like cmd-tabbing
nnoremap <leader><leader> <c-^>

" Visual line nav, not real line nav
" If you wrap lines, vim by default won't let you move down one line to the
" wrapped portion. This fixes that
noremap j gj
noremap k gk
vnoremap j gj
vnoremap k gk

" H to start of line, L to end of line
noremap H ^
noremap L $

" Disable the arrow keys, force ourselves to use VIM navigation keys
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

source ~/dotfiles/.vim/vim-plugins.vim

" Finally the color scheme
set bg=dark
colorscheme molokai

" This will autoreload the vimrc after saving
" the file
if has("autocmd")
  augroup reload_vimrc " {
    autocmd!
    autocmd BufWritePost $MYVIMRC source $MYVIMRC
  augroup END " }
endif

" Include users local vimrc
" This will override anything in this file
" should it be set up above.
if filereadable(expand("~/.vimrc.local"))
    source ~/.vimrc.local
endif

